Merging in components to run on Mac OS
BCaven/creativity-optional pull request #27
Opened 2024-04-02 20:46 UTC by ChadBrow

This should have no effect on running the application on Linux.

2024-04-02 21:06 UTC, BCaven requested changes
this will need to be added back in so the development server can build the vue site

2024-04-02 21:14 UTC, BCaven requested changes, later dismissed
answer the questions sir

2024-04-02 21:14 UTC, BCaven commented on src/macOS_pyaudio.py
eventually we will need to support switching input devices and settings
also, this uses the 0.0.0.0 formatting which will probably not be supported in the final version - but we will have to see, mac might still interpret it correctly even if the server will not recognize 0.0.0.0

2024-04-02 21:14 UTC, BCaven commented on src/package-lock.json
wait, why is there a `package-lock` in the `src/` folder?

2024-04-02 21:16 UTC, BCaven commented
After changing the dockerfile back to building the vue site, this is compatible with linux.
Why was it removed from the mac build again?

It only really matters for development, because production versions will pre-build the vue site

2024-04-15 04:06 UTC, AnarBayanzul approved these changes
looks good to me!

2024-04-15 04:06 UTC, merged